services:
  db:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: 'testingsrootpass'
    ports:
      - ${DB_PORT}:3306
